Lv-648-TAQC-Java-project/codewa648

- src/main/java/com/org/ita/kata/implementation/andriy66/Eigth.java
- src/main/java/com/org/ita/kata/implementation/andriy66/Five.java
- src/main/java/com/org/ita/kata/implementation/andriy66/Seven.java
- src/main/java/com/org/ita/kata/implementation/andriy66/Six.java
> add impl andriy66

- src/main/java/com/org/ita/kata/implementation/Mykhailo5/Five.java
> implemented Find the smallest

- src/main/java/com/org/ita/kata/implementation/Mykhailo5/Five.java
> implemented Artificial Rain

- src/main/java/com/org/ita/kata/implementation/Mykhailo5/Six.java
> implemented task Ranking NBA teams

- src/main/java/com/org/ita/kata/implementation/Pidstavskiy/Five.java
> Implemented Find the smallest task

- src/main/java/com/org/ita/kata/implementation/Pidstavskiy/Five.java
> Implemented Perimeter of squares in a rectangle task

- src/main/java/com/org/ita/kata/implementation/Mykhailo5/Eigth.java
> implemented mpgToKPM

- src/main/java/com/org/ita/kata/implementation/Mykhailo5/Eigth.java
> implemented divisibleBy

- src/main/java/com/org/ita/kata/implementation/Mykhailo5/Eigth.java
> implemented twoDecimalPlaces

- src/main/java/com/org/ita/kata/implementation/Mykhailo5/Eigth.java
> implemented amIWilson

- src/main/java/com/org/ita/kata/implementation/Mykhailo5/Eigth.java
> implemented stringToNumber

- src/main/java/com/org/ita/kata/implementation/Mykhailo5/Eigth.java
> implemented countPositivesSumNegatives

- src/main/java/com/org/ita/kata/implementation/Mykhailo5/Eigth.java
> implemented squareOrSquareRoot

- src/main/java/com/org/ita/kata/implementation/Mykhailo5/Eigth.java
> implemented VolumeOfCuboid

- src/main/java/com/org/ita/kata/implementation/Pidstavskiy/Eigth.java
> Implemented Find numbers which are divisible by given number task

- src/main/java/com/org/ita/kata/implementation/Pidstavskiy/Eigth.java
> Implemented Formatting decimal places task

- src/main/java/com/org/ita/kata/implementation/Pidstavskiy/Eigth.java
> Implemented Convert a String to a Number task

- src/main/java/com/org/ita/kata/implementation/Pidstavskiy/Eigth.java
> Implemented Count of positives / sum of negatives task

- src/main/java/com/org/ita/kata/implementation/Pidstavskiy/Eigth.java
> Implemented To square(root) or not to square(root)

- src/main/java/com/org/ita/kata/implementation/Pidstavskiy/Eigth.java
> Implemented Miles per gallon to kilometers per liter task

- src/main/java/com/org/ita/kata/implementation/Pidstavskiy/Eigth.java
> implemented Volume of Cuboid method

- src/main/java/com/org/ita/kata/implementation/Pidstavskiy/Eigth.java
> Implemented liters method

- src/main/java/com/org/ita/kata/implementation/Mykhailo5/Eigth.java
> implemented task 8.1

- src/test/java/com/org/ita/kata/FiveTest.java
> Implemented test for Number of trailing zeros of N! task

- src/test/java/com/org/ita/kata/EigthTest.java
> Implemented test for Count of positives / sum of negatives task

- src/test/java/com/org/ita/kata/SevenTest.java
> implemented test for Sum of the first nth term of Series

- src/test/java/com/org/ita/kata/SevenTest.java
> nadya101/#415 testNG for newAvg method

- src/main/java/com/org/ita/kata/implementation/Pidstavskiy/Eigth.java
> fix divisibleBy() method

- src/main/java/com/org/ita/kata/implementation/Pidstavskiy/Eigth.java
> fix liters() method

- src/main/java/com/org/ita/kata/implementation/Mykhailo5/Eigth.java
> refactor task divisible by

- src/test/java/com/org/ita/kata/ReadStringArray.java
> implemented test for readStringArray

- src/test/java/com/org/ita/kata/ReadFloatTest.java
> implemented test for readFloat

- src/test/java/com/org/ita/kata/ReadStringTest.java
> Implemented test for readString() method

- src/main/java/com/org/ita/kata/implementation/Mykhailo5/Eigth.java
> fixed method liters
